# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: grpc_protos/console.proto
# plugin: python-betterproto
# This file has been @generated

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from dataclasses import dataclass
else:
    from pydantic.dataclasses import dataclass

from typing import (
    Dict,
    Optional,
)

import betterproto
import grpclib
from betterproto.grpc.grpclib_server import ServiceBase
from pydantic.dataclasses import rebuild_dataclass


@dataclass(eq=False, repr=False)
class ResetCompanyRequest(betterproto.Message):
    """
    reset_company — remove an idle human company (server-only).
     company_id matches GetCompanyList.company_id (internal company index).
    """

    company_id: int = betterproto.uint32_field(1)


@dataclass(eq=False, repr=False)
class ResetCompanyReply(betterproto.Message):
    """Reply for ResetCompany — empty on success; errors via GenericError."""


@dataclass(eq=False, repr=False)
class SettingNewgameRequest(betterproto.Message):
    """setting_newgame — get/set a setting for the next game."""

    name: str = betterproto.string_field(1)
    """
    Setting name as used by the in-game console (e.g. "difficulty.max_loan").
    """

    value: str | None = betterproto.string_field(2, optional=True)
    """
    When set, updates the newgame setting to this value.
     When not set, request is treated as "get".
    """


@dataclass(eq=False, repr=False)
class SettingNewgameReply(betterproto.Message):
    """
    Reply for SettingNewgame — returns the current value after the operation.
    """

    value: str = betterproto.string_field(1)
    """Current value (formatted as a string)."""


@dataclass(eq=False, repr=False)
class SettingRequest(betterproto.Message):
    """setting — get/set a setting for the current game."""

    name: str = betterproto.string_field(1)
    """
    Setting name as used by the in-game console (e.g. "difficulty.max_loan").
    """

    value: str | None = betterproto.string_field(2, optional=True)
    """
    When set, updates the setting to this value for the current game.
     When not set, request is treated as "get".
    """


@dataclass(eq=False, repr=False)
class SettingReply(betterproto.Message):
    """Reply for Setting — returns the current value after the operation."""

    value: str = betterproto.string_field(1)
    """Current value (formatted as a string)."""


@dataclass(eq=False, repr=False)
class RestartRequest(betterproto.Message):
    """restart — restart the game (mirrors dedicated console `restart`)."""

    mode: str | None = betterproto.string_field(1, optional=True)
    """
    When unset or empty: same as `restart` with no extra argument (newgame path, current generation seed).
     "newgame" — explicit newgame restart.
     "current" — restart with current map log dimensions (`SM_RESTARTGAME`).
    """


@dataclass(eq=False, repr=False)
class RestartReply(betterproto.Message):
    """Reply for Restart — empty on success; errors via GenericError."""


class ConsoleStub(betterproto.ServiceStub):
    async def reset_company(
        self,
        reset_company_request: "ResetCompanyRequest",
        *,
        timeout: float | None = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None,
    ) -> "ResetCompanyReply":
        return await self._unary_unary(
            "/openttd.Console/ResetCompany",
            reset_company_request,
            ResetCompanyReply,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def setting_newgame(
        self,
        setting_newgame_request: "SettingNewgameRequest",
        *,
        timeout: float | None = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None,
    ) -> "SettingNewgameReply":
        return await self._unary_unary(
            "/openttd.Console/SettingNewgame",
            setting_newgame_request,
            SettingNewgameReply,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def setting(
        self,
        setting_request: "SettingRequest",
        *,
        timeout: float | None = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None,
    ) -> "SettingReply":
        return await self._unary_unary(
            "/openttd.Console/Setting",
            setting_request,
            SettingReply,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def restart(
        self,
        restart_request: "RestartRequest",
        *,
        timeout: float | None = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None,
    ) -> "RestartReply":
        return await self._unary_unary(
            "/openttd.Console/Restart",
            restart_request,
            RestartReply,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class ConsoleBase(ServiceBase):
    async def reset_company(
        self, reset_company_request: "ResetCompanyRequest"
    ) -> "ResetCompanyReply":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def setting_newgame(
        self, setting_newgame_request: "SettingNewgameRequest"
    ) -> "SettingNewgameReply":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def setting(self, setting_request: "SettingRequest") -> "SettingReply":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def restart(self, restart_request: "RestartRequest") -> "RestartReply":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_reset_company(
        self, stream: "grpclib.server.Stream[ResetCompanyRequest, ResetCompanyReply]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.reset_company(request)
        await stream.send_message(response)

    async def __rpc_setting_newgame(
        self,
        stream: "grpclib.server.Stream[SettingNewgameRequest, SettingNewgameReply]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.setting_newgame(request)
        await stream.send_message(response)

    async def __rpc_setting(
        self, stream: "grpclib.server.Stream[SettingRequest, SettingReply]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.setting(request)
        await stream.send_message(response)

    async def __rpc_restart(
        self, stream: "grpclib.server.Stream[RestartRequest, RestartReply]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.restart(request)
        await stream.send_message(response)

    def __mapping__(self) -> dict[str, grpclib.const.Handler]:
        return {
            "/openttd.Console/ResetCompany": grpclib.const.Handler(
                self.__rpc_reset_company,
                grpclib.const.Cardinality.UNARY_UNARY,
                ResetCompanyRequest,
                ResetCompanyReply,
            ),
            "/openttd.Console/SettingNewgame": grpclib.const.Handler(
                self.__rpc_setting_newgame,
                grpclib.const.Cardinality.UNARY_UNARY,
                SettingNewgameRequest,
                SettingNewgameReply,
            ),
            "/openttd.Console/Setting": grpclib.const.Handler(
                self.__rpc_setting,
                grpclib.const.Cardinality.UNARY_UNARY,
                SettingRequest,
                SettingReply,
            ),
            "/openttd.Console/Restart": grpclib.const.Handler(
                self.__rpc_restart,
                grpclib.const.Cardinality.UNARY_UNARY,
                RestartRequest,
                RestartReply,
            ),
        }
