# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: grpc_protos/script_map.proto
# plugin: python-betterproto
# This file has been @generated

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from dataclasses import dataclass
else:
    from pydantic.dataclasses import dataclass

from typing import (
    Dict,
    Optional,
)

import betterproto
import grpclib
from betterproto.grpc.grpclib_server import ServiceBase
from pydantic.dataclasses import rebuild_dataclass


@dataclass(eq=False, repr=False)
class GetMapSizeXRequest(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class GetMapSizeXReply(betterproto.Message):
    size_x: int = betterproto.int32_field(1)


@dataclass(eq=False, repr=False)
class GetMapSizeYRequest(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class GetMapSizeYReply(betterproto.Message):
    size_y: int = betterproto.int32_field(1)


@dataclass(eq=False, repr=False)
class GetTileIndexRequest(betterproto.Message):
    x: int = betterproto.int32_field(1)
    y: int = betterproto.int32_field(2)


@dataclass(eq=False, repr=False)
class GetTileIndexReply(betterproto.Message):
    tile_index: int = betterproto.uint32_field(1)


class ScriptMapStub(betterproto.ServiceStub):
    async def get_map_size_x(
        self,
        get_map_size_x_request: "GetMapSizeXRequest",
        *,
        timeout: float | None = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None,
    ) -> "GetMapSizeXReply":
        return await self._unary_unary(
            "/openttd.ScriptMap/GetMapSizeX",
            get_map_size_x_request,
            GetMapSizeXReply,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_map_size_y(
        self,
        get_map_size_y_request: "GetMapSizeYRequest",
        *,
        timeout: float | None = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None,
    ) -> "GetMapSizeYReply":
        return await self._unary_unary(
            "/openttd.ScriptMap/GetMapSizeY",
            get_map_size_y_request,
            GetMapSizeYReply,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_tile_index(
        self,
        get_tile_index_request: "GetTileIndexRequest",
        *,
        timeout: float | None = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None,
    ) -> "GetTileIndexReply":
        return await self._unary_unary(
            "/openttd.ScriptMap/GetTileIndex",
            get_tile_index_request,
            GetTileIndexReply,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class ScriptMapBase(ServiceBase):
    async def get_map_size_x(
        self, get_map_size_x_request: "GetMapSizeXRequest"
    ) -> "GetMapSizeXReply":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_map_size_y(
        self, get_map_size_y_request: "GetMapSizeYRequest"
    ) -> "GetMapSizeYReply":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_tile_index(
        self, get_tile_index_request: "GetTileIndexRequest"
    ) -> "GetTileIndexReply":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_get_map_size_x(
        self, stream: "grpclib.server.Stream[GetMapSizeXRequest, GetMapSizeXReply]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_map_size_x(request)
        await stream.send_message(response)

    async def __rpc_get_map_size_y(
        self, stream: "grpclib.server.Stream[GetMapSizeYRequest, GetMapSizeYReply]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_map_size_y(request)
        await stream.send_message(response)

    async def __rpc_get_tile_index(
        self, stream: "grpclib.server.Stream[GetTileIndexRequest, GetTileIndexReply]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_tile_index(request)
        await stream.send_message(response)

    def __mapping__(self) -> dict[str, grpclib.const.Handler]:
        return {
            "/openttd.ScriptMap/GetMapSizeX": grpclib.const.Handler(
                self.__rpc_get_map_size_x,
                grpclib.const.Cardinality.UNARY_UNARY,
                GetMapSizeXRequest,
                GetMapSizeXReply,
            ),
            "/openttd.ScriptMap/GetMapSizeY": grpclib.const.Handler(
                self.__rpc_get_map_size_y,
                grpclib.const.Cardinality.UNARY_UNARY,
                GetMapSizeYRequest,
                GetMapSizeYReply,
            ),
            "/openttd.ScriptMap/GetTileIndex": grpclib.const.Handler(
                self.__rpc_get_tile_index,
                grpclib.const.Cardinality.UNARY_UNARY,
                GetTileIndexRequest,
                GetTileIndexReply,
            ),
        }
