# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: grpc_protos/admin.proto
# plugin: python-betterproto
# This file has been @generated

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from dataclasses import dataclass
else:
    from pydantic.dataclasses import dataclass

from typing import (
    Dict,
    List,
    Optional,
)

import betterproto
import grpclib
from betterproto.grpc.grpclib_server import ServiceBase
from pydantic.dataclasses import rebuild_dataclass


class ServerVisibilityType(betterproto.Enum):
    LOCAL = 0
    PUBLIC = 1
    INVITE_ONLY = 2

    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        from pydantic_core import core_schema

        return core_schema.int_schema(ge=0)


class GameModeType(betterproto.Enum):
    NEW_GAME_MENU = 0
    SCENARIO_EDITOR = 1
    HEIGHTMAP_EDITOR = 2
    SINGLE_GAME = 3
    MULTIPLAYER_CLIENT = 4
    MULTIPLAYER_SERVER = 5
    UNKNOWN = 6

    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        from pydantic_core import core_schema

        return core_schema.int_schema(ge=0)


class NetworkActionType(betterproto.Enum):
    NETWORK_ACTION_JOIN = 0
    NETWORK_ACTION_LEAVE = 1
    NETWORK_ACTION_SERVER_MESSAGE = 2
    NETWORK_ACTION_CHAT = 3
    NETWORK_ACTION_CHAT_COMPANY = 4
    NETWORK_ACTION_CHAT_CLIENT = 5
    NETWORK_ACTION_GIVE_MONEY = 6
    NETWORK_ACTION_NAME_CHANGE = 7
    NETWORK_ACTION_COMPANY_SPECTATOR = 8
    NETWORK_ACTION_COMPANY_JOIN = 9
    NETWORK_ACTION_COMPANY_NEW = 10
    NETWORK_ACTION_KICKED = 11
    NETWORK_ACTION_EXTERNAL_CHAT = 12

    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        from pydantic_core import core_schema

        return core_schema.int_schema(ge=0)


class ChatDestType(betterproto.Enum):
    DESTTYPE_BROADCAST = 0
    DESTTYPE_TEAM = 1
    DESTTYPE_CLIENT = 2

    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        from pydantic_core import core_schema

        return core_schema.int_schema(ge=0)


@dataclass(eq=False, repr=False)
class StartNetworkServerRequest(betterproto.Message):
    server_name: str = betterproto.string_field(1)
    max_clients: int = betterproto.uint32_field(2)
    max_companies: int = betterproto.uint32_field(3)
    visibility_type: "ServerVisibilityType" = betterproto.enum_field(4)
    scenario_path: str = betterproto.string_field(5)
    spectator_player_name: str = betterproto.string_field(6)
    server_password: str = betterproto.string_field(7)
    save_path: str = betterproto.string_field(8)
    script_name: str | None = betterproto.string_field(9, optional=True)
    script_version: int | None = betterproto.uint32_field(10, optional=True)


@dataclass(eq=False, repr=False)
class StartNetworkServerReply(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class GetGameModeRequest(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class GetGameModeReply(betterproto.Message):
    current_mode: "GameModeType" = betterproto.enum_field(1)
    new_mode: "GameModeType" = betterproto.enum_field(2)
    is_dedicated: bool = betterproto.bool_field(3)
    server_name: str = betterproto.string_field(4)


@dataclass(eq=False, repr=False)
class NetworkClient(betterproto.Message):
    client_id: int = betterproto.uint32_field(1)
    client_name: str = betterproto.string_field(2)
    company_id: int = betterproto.uint32_field(3)
    is_spectator: bool = betterproto.bool_field(4)


@dataclass(eq=False, repr=False)
class GetNetworkClientsRequest(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class GetNetworkClientsReply(betterproto.Message):
    clients: list["NetworkClient"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class SendChatMessageRequest(betterproto.Message):
    message: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class SendChatMessageReply(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class SendPrivateChatMessageRequest(betterproto.Message):
    client_id: int = betterproto.uint32_field(1)
    message: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class SendPrivateChatMessageReply(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class PollLastChatMessagesRequest(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class ChatNotification(betterproto.Message):
    received_unix_ms: int = betterproto.uint64_field(1)
    action: "NetworkActionType" = betterproto.enum_field(2)
    desttype: "ChatDestType" = betterproto.enum_field(3)
    client_id: int = betterproto.uint32_field(4)
    message: str = betterproto.string_field(5)


@dataclass(eq=False, repr=False)
class PollLastChatMessagesReply(betterproto.Message):
    messages: list["ChatNotification"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class Company(betterproto.Message):
    company_id: int = betterproto.uint32_field(1)
    company_name: str = betterproto.string_field(2)
    client_ids: list[int] = betterproto.uint32_field(3)


@dataclass(eq=False, repr=False)
class GetCompanyListRequest(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class GetCompanyListReply(betterproto.Message):
    companies: list["Company"] = betterproto.message_field(1)


class AdminStub(betterproto.ServiceStub):
    async def start_network_server(
        self,
        start_network_server_request: "StartNetworkServerRequest",
        *,
        timeout: float | None = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None,
    ) -> "StartNetworkServerReply":
        return await self._unary_unary(
            "/openttd.Admin/StartNetworkServer",
            start_network_server_request,
            StartNetworkServerReply,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_network_clients(
        self,
        get_network_clients_request: "GetNetworkClientsRequest",
        *,
        timeout: float | None = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None,
    ) -> "GetNetworkClientsReply":
        return await self._unary_unary(
            "/openttd.Admin/GetNetworkClients",
            get_network_clients_request,
            GetNetworkClientsReply,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def send_chat_message(
        self,
        send_chat_message_request: "SendChatMessageRequest",
        *,
        timeout: float | None = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None,
    ) -> "SendChatMessageReply":
        return await self._unary_unary(
            "/openttd.Admin/SendChatMessage",
            send_chat_message_request,
            SendChatMessageReply,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def send_private_chat_message(
        self,
        send_private_chat_message_request: "SendPrivateChatMessageRequest",
        *,
        timeout: float | None = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None,
    ) -> "SendPrivateChatMessageReply":
        return await self._unary_unary(
            "/openttd.Admin/SendPrivateChatMessage",
            send_private_chat_message_request,
            SendPrivateChatMessageReply,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def poll_last_chat_messages(
        self,
        poll_last_chat_messages_request: "PollLastChatMessagesRequest",
        *,
        timeout: float | None = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None,
    ) -> "PollLastChatMessagesReply":
        return await self._unary_unary(
            "/openttd.Admin/PollLastChatMessages",
            poll_last_chat_messages_request,
            PollLastChatMessagesReply,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_company_list(
        self,
        get_company_list_request: "GetCompanyListRequest",
        *,
        timeout: float | None = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None,
    ) -> "GetCompanyListReply":
        return await self._unary_unary(
            "/openttd.Admin/GetCompanyList",
            get_company_list_request,
            GetCompanyListReply,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_game_mode(
        self,
        get_game_mode_request: "GetGameModeRequest",
        *,
        timeout: float | None = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None,
    ) -> "GetGameModeReply":
        return await self._unary_unary(
            "/openttd.Admin/GetGameMode",
            get_game_mode_request,
            GetGameModeReply,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class AdminBase(ServiceBase):
    async def start_network_server(
        self, start_network_server_request: "StartNetworkServerRequest"
    ) -> "StartNetworkServerReply":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_network_clients(
        self, get_network_clients_request: "GetNetworkClientsRequest"
    ) -> "GetNetworkClientsReply":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def send_chat_message(
        self, send_chat_message_request: "SendChatMessageRequest"
    ) -> "SendChatMessageReply":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def send_private_chat_message(
        self, send_private_chat_message_request: "SendPrivateChatMessageRequest"
    ) -> "SendPrivateChatMessageReply":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def poll_last_chat_messages(
        self, poll_last_chat_messages_request: "PollLastChatMessagesRequest"
    ) -> "PollLastChatMessagesReply":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_company_list(
        self, get_company_list_request: "GetCompanyListRequest"
    ) -> "GetCompanyListReply":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_game_mode(
        self, get_game_mode_request: "GetGameModeRequest"
    ) -> "GetGameModeReply":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_start_network_server(
        self,
        stream: "grpclib.server.Stream[StartNetworkServerRequest, StartNetworkServerReply]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.start_network_server(request)
        await stream.send_message(response)

    async def __rpc_get_network_clients(
        self,
        stream: "grpclib.server.Stream[GetNetworkClientsRequest, GetNetworkClientsReply]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_network_clients(request)
        await stream.send_message(response)

    async def __rpc_send_chat_message(
        self,
        stream: "grpclib.server.Stream[SendChatMessageRequest, SendChatMessageReply]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.send_chat_message(request)
        await stream.send_message(response)

    async def __rpc_send_private_chat_message(
        self,
        stream: "grpclib.server.Stream[SendPrivateChatMessageRequest, SendPrivateChatMessageReply]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.send_private_chat_message(request)
        await stream.send_message(response)

    async def __rpc_poll_last_chat_messages(
        self,
        stream: "grpclib.server.Stream[PollLastChatMessagesRequest, PollLastChatMessagesReply]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.poll_last_chat_messages(request)
        await stream.send_message(response)

    async def __rpc_get_company_list(
        self,
        stream: "grpclib.server.Stream[GetCompanyListRequest, GetCompanyListReply]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_company_list(request)
        await stream.send_message(response)

    async def __rpc_get_game_mode(
        self, stream: "grpclib.server.Stream[GetGameModeRequest, GetGameModeReply]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_game_mode(request)
        await stream.send_message(response)

    def __mapping__(self) -> dict[str, grpclib.const.Handler]:
        return {
            "/openttd.Admin/StartNetworkServer": grpclib.const.Handler(
                self.__rpc_start_network_server,
                grpclib.const.Cardinality.UNARY_UNARY,
                StartNetworkServerRequest,
                StartNetworkServerReply,
            ),
            "/openttd.Admin/GetNetworkClients": grpclib.const.Handler(
                self.__rpc_get_network_clients,
                grpclib.const.Cardinality.UNARY_UNARY,
                GetNetworkClientsRequest,
                GetNetworkClientsReply,
            ),
            "/openttd.Admin/SendChatMessage": grpclib.const.Handler(
                self.__rpc_send_chat_message,
                grpclib.const.Cardinality.UNARY_UNARY,
                SendChatMessageRequest,
                SendChatMessageReply,
            ),
            "/openttd.Admin/SendPrivateChatMessage": grpclib.const.Handler(
                self.__rpc_send_private_chat_message,
                grpclib.const.Cardinality.UNARY_UNARY,
                SendPrivateChatMessageRequest,
                SendPrivateChatMessageReply,
            ),
            "/openttd.Admin/PollLastChatMessages": grpclib.const.Handler(
                self.__rpc_poll_last_chat_messages,
                grpclib.const.Cardinality.UNARY_UNARY,
                PollLastChatMessagesRequest,
                PollLastChatMessagesReply,
            ),
            "/openttd.Admin/GetCompanyList": grpclib.const.Handler(
                self.__rpc_get_company_list,
                grpclib.const.Cardinality.UNARY_UNARY,
                GetCompanyListRequest,
                GetCompanyListReply,
            ),
            "/openttd.Admin/GetGameMode": grpclib.const.Handler(
                self.__rpc_get_game_mode,
                grpclib.const.Cardinality.UNARY_UNARY,
                GetGameModeRequest,
                GetGameModeReply,
            ),
        }


rebuild_dataclass(StartNetworkServerRequest)  # type: ignore
rebuild_dataclass(GetGameModeReply)  # type: ignore
rebuild_dataclass(GetNetworkClientsReply)  # type: ignore
rebuild_dataclass(ChatNotification)  # type: ignore
rebuild_dataclass(PollLastChatMessagesReply)  # type: ignore
rebuild_dataclass(GetCompanyListReply)  # type: ignore
