# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: grpc_protos/script_generic.proto
# plugin: python-betterproto
# This file has been @generated

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from dataclasses import dataclass
else:
    from pydantic.dataclasses import dataclass

import betterproto
from pydantic.dataclasses import rebuild_dataclass


class ErrorCode(betterproto.Enum):
    """
    Error codes for RPC operations
     These map to gRPC status codes on the client side:
     - OK (0) -> grpc::OK
     - INVALID_ARGUMENT (1) -> grpc::INVALID_ARGUMENT
     - OUT_OF_RANGE (2) -> grpc::OUT_OF_RANGE
     - NOT_FOUND (3) -> grpc::NOT_FOUND
     - INTERNAL (4) -> grpc::INTERNAL
     - UNIMPLEMENTED (5) -> grpc::UNIMPLEMENTED
    """

    ERROR_NONE = 0
    ERROR_INVALID_ARGUMENT = 1
    ERROR_OUT_OF_RANGE = 2
    ERROR_NOT_FOUND = 3
    ERROR_INTERNAL = 4
    ERROR_UNIMPLEMENTED = 5

    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        from pydantic_core import core_schema

        return core_schema.int_schema(ge=0)


@dataclass(eq=False, repr=False)
class GenericError(betterproto.Message):
    """
    GenericError is used by RPC handlers to report errors
     When error_code is ERROR_NONE (0), no error occurred
    """

    error_code: "ErrorCode" = betterproto.enum_field(1)
    error_summary: str = betterproto.string_field(2)


rebuild_dataclass(GenericError)  # type: ignore
