# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: grpc_protos/script_generic.proto
# plugin: python-betterproto
# This file has been @generated

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from dataclasses import dataclass
else:
    from pydantic.dataclasses import dataclass

from typing import (
    Dict,
    Optional,
)

import betterproto
import grpclib
from betterproto.grpc.grpclib_server import ServiceBase
from pydantic.dataclasses import rebuild_dataclass


class ErrorCode(betterproto.Enum):
    """
    Error codes for RPC operations
     These map to gRPC status codes on the client side:
     - OK (0) -> grpc::OK
     - INVALID_ARGUMENT (1) -> grpc::INVALID_ARGUMENT
     - OUT_OF_RANGE (2) -> grpc::OUT_OF_RANGE
     - NOT_FOUND (3) -> grpc::NOT_FOUND
     - INTERNAL (4) -> grpc::INTERNAL
     - UNIMPLEMENTED (5) -> grpc::UNIMPLEMENTED
    """

    ERROR_NONE = 0
    ERROR_INVALID_ARGUMENT = 1
    ERROR_OUT_OF_RANGE = 2
    ERROR_NOT_FOUND = 3
    ERROR_INTERNAL = 4
    ERROR_UNIMPLEMENTED = 5

    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        from pydantic_core import core_schema

        return core_schema.int_schema(ge=0)


@dataclass(eq=False, repr=False)
class GenericError(betterproto.Message):
    """
    GenericError is used by RPC handlers to report errors
     When error_code is ERROR_NONE (0), no error occurred
    """

    error_code: "ErrorCode" = betterproto.enum_field(1)
    error_summary: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class GetLastIntResultRequest(betterproto.Message):
    """
    GetLastIntResult - retrieves the last integer result from script operations
    """


@dataclass(eq=False, repr=False)
class GetLastIntResultReply(betterproto.Message):
    result: int = betterproto.int32_field(1)
    """
    The last integer result from a script operation.
     This could be a GoalID, SignID, VehicleID, or any other ID type
     that was returned via Squirrel::InsertResult(int).
    """


class ScriptGenericStub(betterproto.ServiceStub):
    async def get_last_int_result(
        self,
        get_last_int_result_request: "GetLastIntResultRequest",
        *,
        timeout: float | None = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None,
    ) -> "GetLastIntResultReply":
        return await self._unary_unary(
            "/openttd.ScriptGeneric/GetLastIntResult",
            get_last_int_result_request,
            GetLastIntResultReply,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class ScriptGenericBase(ServiceBase):
    async def get_last_int_result(
        self, get_last_int_result_request: "GetLastIntResultRequest"
    ) -> "GetLastIntResultReply":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_get_last_int_result(
        self,
        stream: "grpclib.server.Stream[GetLastIntResultRequest, GetLastIntResultReply]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_last_int_result(request)
        await stream.send_message(response)

    def __mapping__(self) -> dict[str, grpclib.const.Handler]:
        return {
            "/openttd.ScriptGeneric/GetLastIntResult": grpclib.const.Handler(
                self.__rpc_get_last_int_result,
                grpclib.const.Cardinality.UNARY_UNARY,
                GetLastIntResultRequest,
                GetLastIntResultReply,
            ),
        }


rebuild_dataclass(GenericError)  # type: ignore
