# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: grpc_protos/script_goal.proto
# plugin: python-betterproto
# This file has been @generated

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from dataclasses import dataclass
else:
    from pydantic.dataclasses import dataclass

from typing import (
    Dict,
    Optional,
)

import betterproto
import grpclib
from betterproto.grpc.grpclib_server import ServiceBase
from pydantic.dataclasses import rebuild_dataclass


class GoalType(betterproto.Enum):
    GT_NONE = 0
    GT_TILE = 1
    GT_INDUSTRY = 2
    GT_TOWN = 3
    GT_COMPANY = 4
    GT_STORY_PAGE = 5

    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        from pydantic_core import core_schema

        return core_schema.int_schema(ge=0)


@dataclass(eq=False, repr=False)
class NewGoalRequest(betterproto.Message):
    company: int = betterproto.int32_field(1)
    goal_text: str = betterproto.string_field(2)
    goal_type: "GoalType" = betterproto.enum_field(3)
    destination: int = betterproto.int64_field(4)
    goal_global: bool = betterproto.bool_field(5)


@dataclass(eq=False, repr=False)
class NewGoalReply(betterproto.Message):
    goal_id: int = betterproto.uint32_field(1)


class ScriptGoalStub(betterproto.ServiceStub):
    async def new(
        self,
        new_goal_request: "NewGoalRequest",
        *,
        timeout: float | None = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None,
    ) -> "NewGoalReply":
        return await self._unary_unary(
            "/openttd.ScriptGoal/New",
            new_goal_request,
            NewGoalReply,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class ScriptGoalBase(ServiceBase):
    async def new(self, new_goal_request: "NewGoalRequest") -> "NewGoalReply":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_new(
        self, stream: "grpclib.server.Stream[NewGoalRequest, NewGoalReply]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.new(request)
        await stream.send_message(response)

    def __mapping__(self) -> dict[str, grpclib.const.Handler]:
        return {
            "/openttd.ScriptGoal/New": grpclib.const.Handler(
                self.__rpc_new,
                grpclib.const.Cardinality.UNARY_UNARY,
                NewGoalRequest,
                NewGoalReply,
            ),
        }


rebuild_dataclass(NewGoalRequest)  # type: ignore
