# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: grpc_protos/script_company.proto
# plugin: python-betterproto
# This file has been @generated

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from dataclasses import dataclass
else:
    from pydantic.dataclasses import dataclass

from typing import (
    Dict,
    Optional,
)

import betterproto
import grpclib
from betterproto.grpc.grpclib_server import ServiceBase
from pydantic.dataclasses import rebuild_dataclass


@dataclass(eq=False, repr=False)
class GetQuarterlyCompanyValueRequest(betterproto.Message):
    company: int = betterproto.int32_field(1)
    quarter: int = betterproto.int32_field(2)


@dataclass(eq=False, repr=False)
class GetQuarterlyCompanyValueReply(betterproto.Message):
    company_value: int = betterproto.int64_field(1)


class ScriptCompanyStub(betterproto.ServiceStub):
    async def get_quarterly_company_value(
        self,
        get_quarterly_company_value_request: "GetQuarterlyCompanyValueRequest",
        *,
        timeout: float | None = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None,
    ) -> "GetQuarterlyCompanyValueReply":
        return await self._unary_unary(
            "/openttd.ScriptCompany/GetQuarterlyCompanyValue",
            get_quarterly_company_value_request,
            GetQuarterlyCompanyValueReply,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class ScriptCompanyBase(ServiceBase):
    async def get_quarterly_company_value(
        self, get_quarterly_company_value_request: "GetQuarterlyCompanyValueRequest"
    ) -> "GetQuarterlyCompanyValueReply":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_get_quarterly_company_value(
        self,
        stream: "grpclib.server.Stream[GetQuarterlyCompanyValueRequest, GetQuarterlyCompanyValueReply]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_quarterly_company_value(request)
        await stream.send_message(response)

    def __mapping__(self) -> dict[str, grpclib.const.Handler]:
        return {
            "/openttd.ScriptCompany/GetQuarterlyCompanyValue": grpclib.const.Handler(
                self.__rpc_get_quarterly_company_value,
                grpclib.const.Cardinality.UNARY_UNARY,
                GetQuarterlyCompanyValueRequest,
                GetQuarterlyCompanyValueReply,
            ),
        }
