[workspace]
name = "ottd-grpc-server"
channels = ["conda-forge"]
platforms = ["linux-aarch64"]

[dependencies]
cmake = ">=4.3.3,<5"
cxx-compiler = ">=1.11.0,<2"
make = ">=4.4.1,<5"
spdlog = ">=1.17.0,<2"
abseil-cpp = "*"
libprotobuf = "*"
protobuf = "*"
grpcio = "*"
libgrpc = "*"
boost = "*"

